[package]
name = "nvm-main"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["lib", "dylib"]

[dependencies]
spirv-std = { git = "https://github.com/EmbarkStudios/rust-gpu", features = ["glam"] }
glam = { version = ">=0.17, <=0.20", default-features = false, features = ["libm"] }
